### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/pwa-helpers#11]
These helpers look awfully helpful already, would love to use them, publishing on npm is highly appreciated 😻

**Comment by notwaldorf** [comment]
Sure thing! We'll definitely publish them once they settle a bit (we've barely stopped renaming the helpers every week 😅)

**Comment by Dabolus** [comment]
+1, having them on npm would be really helpful, as currently there is no way to install them on yarn (or at least I didn't find a way 😅). I tried installing them directly using the repo, but seems like yarn doesn't like the empty version field in `package.json`. Looking forward to see them published!

**Comment by frankiefu** [comment]
It's published: https://www.npmjs.com/package/pwa-helpers
