### ISSUE TITLE
Context properties for webcomponents

### ISSUE THREAD

**Issue by askbeka** [Polymer/pwa-helpers#26]
I have created a solution for passing down context in DOM, called it [wc-context], no packaging yet, its coming soon. In mean time want to get some feedback. There is a Redux demo with connect mixin implementation example. Thanks.

**Comment by notwaldorf** [comment]
This sounds very specific to webcomponents -- this repo is for small helpers that are generic to PWAs, and not necessarily web components. Passing down context between web components sounds like it might be suited better to a library, not to this repo.

**Comment by askbeka** [comment]
@notwaldorf But, connect-mixin.js?
