### ISSUE TITLE
force routing

### ISSUE THREAD

**Issue by mrherndon** [Polymer/pwa-helpers#29]
I know this is only a simple router.  But, I was trying to create a password-protected area of a site.  I was attempting to run a quick check of the firebase user on navigation to the page and if there was no logged in user, force navigate them back to the homepage.  I admit this is a little user-hostile, perhaps an error message on the page would be more appropriate.
The other use case is the exact opposite and less hostile, If they are on the home page and sign in, I assume they are going to the user dashboard, so I want to force navigate there.
 I can't seem to work out a way to force nav without getting the router confused or the state mixed up in redux.  Am I missing something, or is this just beyond the scope of this router?

**Comment by web-padawan** [comment]
As you mentioned, this is the really simple router and it is good as long as you want to use Redux actions and write all the logic yourself.

For your use cases, I suggest you to try [vaadin-router](https://github.com/vaadin/vaadin-router) w

**Comment by mrherndon** [comment]
That's pretty clever and much more consistent than what I ended up with.  The great benefit with your method here is that it can be triggered the same from anywhere.  

Thanks for the assist @jsilvermist!

**Comment by notwaldorf** [comment]
Yup, that's totally the way to do it. I'll send a PR to add a comment note about that.
