### ISSUE TITLE
Plan to make it a scoped package

### ISSUE THREAD

**Issue by motss** [Polymer/pwa-helpers#34]
Curious to know if this package will eventually become a scope package like `@polymer/pwa-helpers` instead of `pwa-helpers`?

**Comment by frankiefu** [comment]
@motss We have talked about this but have not made the final decision yet. I am hoping we can have the decision in the next month or two.

**Comment by motss** [comment]
Cool. Thanks for answering this. Glad to know that the team is making good progress. 👍

**Comment by frankiefu** [comment]
We decided to make it not a scoped package under `@polymer`. Similar to lit-element and lit-html.
