### ISSUE TITLE
Typings may not be correct when using decorators

### ISSUE THREAD

**Issue by anoblet** [Polymer/pwa-helpers#57]
Description
Some decorators, In my case 'customElement' from lit-element throw an error when using mixins.

Live Demo
https://stackblitz.com/edit/lit-element-hello-world-zepmzz?file=page-one.ts

Steps to Reproduce
Add customElement decorator to a class
Use the connect mixin
Expected Results
No error

Actual Results
We receive the error:

  Type 'typeof MyElement' is not assignable to type 'Constructor<HTMLElement>'.
    Type 'MyElement' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 235 more.```

### Browsers Affected

- [ *] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.0.0-rc2
- webcomponents: v2.2.3

**Comment by anoblet** [comment]
@justinfagnani

**Comment by frankiefu** [comment]
The types in [`connect` mixin](https://github.com/Polymer/pwa-helpers/blob/master/src/connect-mixin.ts) seems fine. I ran the [typescript template](https://github.com/Polymer/pwa-starter-kit/tree/template-typescript) of PWA Starter Kit and [my-app.ts](https://github.com/Polymer/pwa-starter-kit/blob/template-typescript/src/components/my-app.ts#L41) seems to compile correctly without error.

**Comment by anoblet** [comment]
Try adding the customElement decorator to a class.

**Comment by frankiefu** [comment]
Yeah I did this:
```
@customElement('my-app')
export class MyApp extends connect(store)(LitElement) {
  @property({type: String})
  appTitle = '';
```
and it complied successfully without error.

**Comment by frankiefu** [comment]
@anoblet Are you still having issue? If you are can you please provide a simple reproducible test on Stackblitz/Glitch/jsbin so we can take a look?

**Comment by anoblet** [comment]
Sorry for the delay. I've stopped relying on mixins for the most part. Last time I checked, when I tried to create a repo everything worked so something must have been off on my side.
